### ISSUE TITLE
Backdrop not working 

### ISSUE THREAD

**Issue by uzairleo** [daadu/backdrop#11]
Hi there recently or a month ago i used the backdrop package which was quite interesting experience but now again i am opening and then running the same project without doing any changes to it. Now its giving me this error 
 canRequestFocus: isBackPanelVisible,
      ^^^^^^^^^^^^^^^
as shown in the screenshot i was thinking it may be with only this project lets try the backdrop  in a new project but again its not running and giving me the same error can u please sir fix this bcoz i really need your this backdrop package:

![Screenshot (935)](https://user-images.githubusercontent.com/52172428/79904203-c6af6680-842d-11ea-8754-bfa05b92640d.png)

**Comment by WieFel** [comment]
Just tried to reproduce this error using backdrop v0.2.13 in an empty flutter app, but I can't reproduce the error.

Which flutter version are you using?<br/>
Please post the output of `flutter doctor`

**Comment by uzairleo** [comment]
The version i m using is 0.2.13 but now i changed that to    backdrop: any but still the same result 
here is my flutter doctor output
PS F:\Practice Flutter\top10_flutter_widgets> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.778], locale en-US)   

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[!] IntelliJ IDEA Community Edition (version 2019.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
[√] VS Code (version 1.44.2)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by uzairleo** [comment]
and here is the complete output
PS F:\Practice Flutter\top10_flutter_widgets> flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.778], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at C:\flutter
    • Framework revision 68587a0916 (7 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0        

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\UzairLeo\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 191.7830
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\UzairLeo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 5.1.1 (API 22) (emulator)

! Doctor found issues in 1 category.
PS F:\Practice Flutter\top10_flutter_widgets>

**Comment by WieFel** [comment]
Maybe try to upgrade flutter using `flutter upgrade` and try to run the app again with the new version of flutter.

**Comment by uzairleo** [comment]
ok w8 i m trying  flutter upgrade

**Comment by uzairleo** [comment]
problem solved thanks actually the problem is that
` dependOnInheritedWidgetOfExactType needs at least v1.12.1`  and i was on `flutter v1.9.1` but now after upgrade its runing 
thanks dude :octocat:
